### ISSUE TITLE
Failed vkCreateDescriptorPool on Intel Core i5-4200U

### ISSUE THREAD

**Issue by Pctg-x8** [Pctg-x8/hardgrad_extent#10]
`VK_DEBUG_REPORT_INFORMATION_BIT_EXT`を立てるとvkCreateDescriptorPoolの内部でエラーが発生する(立てないと発生しない謎仕様)

**Comment by discosultan** [comment]
I'm having a similar issue where the `vkCreateDescriptorPool` fails with **error code -1000011001** (`VK_ERROR_VALIDATION_FAILED_EXT`) **only if** I've created a `VkDebugReportCallbackExt` on the `VkInstance` with `VK_DEBUG_REPORT_INFORMATION_BIT_EXT` set.

There are no errors/warnings raised by the LunarG standard validation layers.
